#!/bin/bash

lab="$HOME/lab6/task2"


#echo "" > log1
#for ((k=1; k<6; k++)); do
	log1="$lab/log12.1"
	echo "">"$log1"
	for ((i=1;i<19;i++)); do
		echo "data for N=$i" >> "$log1"
		echo "data for N=$i"
 	 	for ((j=1;j<11;j++)); do
			(time bash startparallel $i) 2>> "$log1"
  		done
	done
#done

	log1="$lab/log11.1"
	echo "">"$log1"
	for ((i=1;i<21;i++)); do
		echo "data for N=$i" >> "$log1"
		echo "data for N=$i"
 	 	for ((j=1;j<11;j++)); do
			(time bash start $i) 2>> "$log1"
  		done
	done
