#!/bin/bash

backupFile=$(ls "/home/mgvvst" | grep ^Backup- | sort | tail -n1 | cut -d "-" -f 2,3,4)
restore="/home/mgvvst/restore"
backupFile="/home/mgvvst/Backup-$backupFile"
for fl in $(ls -1 $backupFile -p | grep -v /)
do
	path="$backupFile/$fl"
	rx='^.*[0-9]{4}-[0-9]{2}-[0-9]{2}$'
	if [[ ! $path =~  $rx ]]; then
		cp $path $restore	
	fi 
done

