#!/bin/bash

echo "" > iv.log
pids=$(ps -ef | awk '{print $2}')
for pid in $pids
do
	if [[ -d "/proc/$pid" ]];then
		ppid=$(cat /proc/$pid/status | awk '{ if( $1 == "PPid:") print $2 }')
		sum=$(cat /proc/$pid/sched | awk '{if ( $1 == "se.sum_exec_runtime" ) print $3}')
		switch=$(cat /proc/$pid/sched | awk '{if ( $1 == "nr_switches" ) print $3}')
		art=$(echo "$sum / $switch" | bc -l)
		echo "$pid $ppid $art"
	fi
done | sort -n -k2 | awk '{ print "ProcesseID=" $1 " : Parent_ProccesID=" $2 " : Average_Running_Time=" $3 }' > iv.log
cat iv.log
