#!/bin/bash

echo "" >  v.log
awk -v prevpid="0" '{

gsub("Parent_ProccesID=", "");
gsub("Average_Running_Time=", "");
if (prevpid != $3){
	print "Average_Children_of_ParentIdD=" prevpid " is " (sum/n);
	prevpid=$3;
	sum=$5;
	n=1;
}else {
	sum+=$5;
	n++;
}
print $1, $2, "Parent_ProccesID=" $3, $4, "Average_Running_Time=" $5;

}
END {
print "Average_Children_of_ParentID=" prevpid " is " (sum/n);
}' iv.log >> v.log
cat v.log
