#!/bin/bash

N=$1
SALT=1000007

filename="bigfile$N"
cp "mainbigfile" "$filename"

echo "-1" >> "$filename"
while read -r line;
do
  [[ $line == "-1" ]] && break
  echo "$(( (2 * line) % SALT ))" >> "$filename"
done < "$filename"
