#!/bin/bash 

lab="$HOME/lab6"
log1="$lab/log21"
echo "">"$log1"

for ((i=1; i<21; i++))
do
	echo "data for N=$i" >> "$log1"
	echo "data for N=$i"
	for ((j=0; j<10; j++))
	do
		(time bash runfib $i) 2>> "$log1"
	done
done
