#!/bin/bash 

lab="$HOME/lab6"
log1="$lab/log21.1"
log2="$lab/log21.2"
log3="$lab/log21.3"
log4="$lab/log21.4"
log5="$lab/log21.5"
#2 proc posledovat
for ((k=1;k<6;k++))
do
	log1="$lab/log21.$k"
	echo "">"$log1"
	for ((i=1; i<21; i++))
	do
		echo "data for N=$i" >> "$log1"
		echo "data for N=$i"
		for ((j=0; j<10; j++))
		do
			(time bash runfib $i) 2>> "$log1"
		done
	done
done

